version: '3.4'

services:
  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "20000:80"

  taskmanager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "20001:80"

