version: '3.4'

services:
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  taskmanager:
    image: ${DOCKER_REGISTRY-}taskmanager
    build:
      context: .
      dockerfile: TaskManager/Dockerfile

